@isTest
public class fedexComWsTrackV18TEST {
 @isTest static void test1() {
        Test.setMock(WebServiceMock.class, new fedexComWsTrackV18MockImpl());
        fedexComWsTrackV18 parentObject = new fedexComWsTrackV18();
    
new fedexComWsTrackV18.TrackSplitShipmentPart();
new fedexComWsTrackV18.TrackNotificationPackage();
new fedexComWsTrackV18.CustomerExceptionRequestDetail();
new fedexComWsTrackV18.Address();
new fedexComWsTrackV18.TrackPayment();
new fedexComWsTrackV18.ShipmentEventNotificationSpecification();
new fedexComWsTrackV18.DeliveryOptionEligibilityDetail();
new fedexComWsTrackV18.ContentRecord();
new fedexComWsTrackV18.TrackDetail();
new fedexComWsTrackV18.Measure();
new fedexComWsTrackV18.TrackingDocumentDispositionDetail();
new fedexComWsTrackV18.Distance();
new fedexComWsTrackV18.TrackingDocumentSpecification();
new fedexComWsTrackV18.EdtExciseCondition();
new fedexComWsTrackV18.AppointmentTimeDetail();
new fedexComWsTrackV18.TrackingSignatureProofOfDeliveryDetail();
new fedexComWsTrackV18.TrackEvent();
new fedexComWsTrackV18.TrackInformationNoteDetail();
new fedexComWsTrackV18.TrackSpecialInstruction();
new fedexComWsTrackV18.TrackingBillOfLadingDocumentDetail();
new fedexComWsTrackV18.TrackServiceDescriptionDetail();
new fedexComWsTrackV18.Weight();
new fedexComWsTrackV18.TrackingDocument();
new fedexComWsTrackV18.DocumentPart();
new fedexComWsTrackV18.LocalTimeRange();
new fedexComWsTrackV18.ShipmentEventNotificationDetail();
new fedexComWsTrackV18.TrackStatusDetail();
new fedexComWsTrackV18.TrackAdvanceNotificationDetail();
new fedexComWsTrackV18.TrackChargeDetail();
new fedexComWsTrackV18.TrackReconciliation();
new fedexComWsTrackV18.TrackSelectionDetail();
new fedexComWsTrackV18.NotificationParameter();
new fedexComWsTrackV18.AppointmentDetail();
new fedexComWsTrackV18.SpecialInstructionStatusDetail();
new fedexComWsTrackV18.StringBarcode();
new fedexComWsTrackV18.TrackingFreightBillingDocumentDetail();
new fedexComWsTrackV18.TrackOtherIdentifierDetail();
new fedexComWsTrackV18.TrackReply();
new fedexComWsTrackV18.AvailableImagesDetail();
new fedexComWsTrackV18.NaftaCommodityDetail();
new fedexComWsTrackV18.TrackNotificationRecipientDetail();
new fedexComWsTrackV18.Notification();
new fedexComWsTrackV18.SendNotificationsRequest();
new fedexComWsTrackV18.Money();
new fedexComWsTrackV18.DateRange();
new fedexComWsTrackV18.Commodity();
new fedexComWsTrackV18.WebAuthenticationCredential();
new fedexComWsTrackV18.GetTrackingDocumentsRequest();
new fedexComWsTrackV18.TransactionDetail();
new fedexComWsTrackV18.Localization();
new fedexComWsTrackV18.WebAuthenticationDetail();
new fedexComWsTrackV18.ClientDetail();
new fedexComWsTrackV18.TrackSpecialHandling();
new fedexComWsTrackV18.VersionId();
new fedexComWsTrackV18.NotificationDetail();
new fedexComWsTrackV18.TrackReturnDetail();
new fedexComWsTrackV18.ShipmentNotificationFormatSpecification();
new fedexComWsTrackV18.PagingDetail();
new fedexComWsTrackV18.SendNotificationsReply();
new fedexComWsTrackV18.Dimensions();
new fedexComWsTrackV18.PieceCountVerificationDetail();
new fedexComWsTrackV18.TrackingDateOrTimestamp();
new fedexComWsTrackV18.FaxDetail();
new fedexComWsTrackV18.TrackPackageIdentifier();
new fedexComWsTrackV18.Contact();
new fedexComWsTrackV18.CompletedTrackDetail();
new fedexComWsTrackV18.TrackRequest();
new fedexComWsTrackV18.TrackingDocumentFormat();
new fedexComWsTrackV18.TrackingDocumentEmailDetail();
new fedexComWsTrackV18.CustomsOptionDetail();
new fedexComWsTrackV18.EMailDetail();
new fedexComWsTrackV18.GetTrackingDocumentsReply();
new fedexComWsTrackV18.TrackPackagingDescriptionDetail();
new fedexComWsTrackV18.ContactAndAddress();
new fedexComWsTrackV18.SignatureImageDetail();
new fedexComWsTrackV18.TrackStatusAncillaryDetail();
new fedexComWsTrackV18.TrackServicePort();
 }
     @isTest static void test2(){
        Test.setMock(WebServiceMock.class, new fedexComWsTrackV18MockImpl());
        fedexComWsTrackV18.TrackServicePort x = new fedexComWsTrackV18.TrackServicePort();
        x.track(null,null,null,null,null);

    }
}